apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
spec:
  selector:
    app: guestbook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: LoadBalancer
